version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
